project_id = "virykbuoqfepmsbbvady"

[functions.payments]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.signicat-bankid-start]
verify_jwt = false

[functions.signicat-bankid-callback]
verify_jwt = false